apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentname }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "my-rds-instance.cev6sku0ehtc.us-east-1.rds.amazonaws.com"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secrets.name }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secrets.name }}
                  key: password
            - name: DB_NAME
              value: "appdb"

