apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.servicename }}
spec:
  type: {{ .Values.frontend.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000